### ISSUE TITLE
Doesn't install.

### ISSUE THREAD

**Issue by nkh** [Corion/App-Mojo-AssetReloader#1]
```
You are visiting the local directory
  '.'
  without lock, take care that concurrent processes do not do likewise.
Reading '/home/nadim/.cpan/Metadata'
  Database was generated on Thu, 31 Aug 2023 12:17:02 GMT
You are visiting the local directory
  '/tmp/nadim/cdt_wTyih/App-Mojo-AssetReloader/.'
  without lock, take care that concurrent processes do not do likewise.
  /tmp/nadim/cdt_wTyih/App-Mojo-AssetReloader/.
  Has already been unwrapped into directory /tmp/nadim/cdt_wTyih/App-Mojo-AssetReloader/.
CPAN: CPAN::Meta::Requirements loaded ok (v2.140)
CPAN: Parse::CPAN::Meta loaded ok (v2.150010)
CPAN: CPAN::Meta loaded ok (v2.150010)
CPAN: Module::CoreList loaded ok (v5.20210520)
Package contains both files[META.yml MANIFEST.SKIP MANIFEST Changes README.mkdn META.json .gitignore README README.md] and directories[xt t scripts lib .git demo]; not recognized as a perl package, giving up
Configuring /tmp/nadim/cdt_wTyih/App-Mojo-AssetReloader/. with Makefile.PL
Directory '/tmp/nadim/cdt_wTyih/App-Mojo-AssetReloader/.' not below /home/nadim/.cpan/build, will not store persistent state
Running make for /tmp/nadim/cdt_wTyih/App-Mojo-AssetReloader/.
make: *** No targets specified and no makefile found.  Stop.
  /tmp/nadim/cdt_wTyih/App-Mojo-AssetReloader/.
  /usr/bin/make -- NOT OK
  ```

**Comment by Corion** [comment]
Whoops! I had a really old version here on Github, thanks for notifying me!

I've pushed the most recent changes and now it should also install as described!

**Comment by nkh** [comment]
If you are on the "Perl community" FB group there's a discussion, I started about a functionality I've been looking for that I thought your module would be a good solution to.  I'm sure your input will be appreciated there.

https://www.facebook.com/groups/perlcommunity/posts/1523146545159633/

**Comment by Corion** [comment]
I don't do Facebook.

**Comment by nkh** [comment]
Then I'll resume it quickly and if you have any input I will relay it as more may be interested.

I was looking for a web server that would:
- serve a directory, showing the files in the directory
- serve the files in the directory
- use live reload if the contents of the directory change
- use live reload if a file being viewed is changed
- the possibility to stop the live reloads with a button

The discussion drifted towards how to do it in Plack or Mojo, mainly talking about websocket, SSE wasn't named (my bad I didn't know about it)

**Comment by Corion** [comment]
SSE is fickle, but for local development it could work. My approach is somewhat Mojo-specific, but there is nothing that would prevent doing the same with Plack. I was merely too lazy to write this as a Plack middleware, and don't have the need.

I don't think this code makes sense to release as a program to CPAN, but if there is interest, it's easy for me to release it there.

**Comment by nkh** [comment]
There's aready a middlewear for it in Plack, btw I don't think people care if it's' Plack or Mojo, and this app that serves files but doesn't serve a directory listing https://metacpan.org/dist/Plack-App-MCCS/view/bin/mccs.

Someone posted some code about putting them together, I'm no Plack nor Mojo developer, I tied it but it didn't work.

I spend a good part of the day trying to find an already made solution and must have tried 20 different server application, none did what I was looking for. I just found 2 more this morning and will test them later.
